version: '3.8'
services:
  td-main-db:
    container_name: td-main-db
    env_file:
      - .env
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "${EXTERNAL_PORT}:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}