BD_SOURCE_URL: jdbc:postgresql://td-main-db:5432/td_main

BD_DRIVER: org.postgresql.Driver

BD_USER: server_user

BD_PASSWORD: qwerty

LIQUIBASE_SCHEMA: liquibase

MAIN_SCHEMA: main

LIQUIBASE_CHANGE_LOG: db/changelog/db.changelog-master.xml